version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1.8}
      dockerfile: .docker/php/Dockerfile
    working_dir: /symfony_app
    user: ${UID:-1000}:${GID:-1000}
    environment:
      PHP_IDE_CONFIG: "serverName=DevServer"
    volumes:
      - ./:/symfony_app
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
    container_name: symf_test_php

  db:
    image: "postgres:${POSTGRES_VERSION:-14}"
    ports:
      - "5432:5432"
    container_name: symf_test_db
    environment:
      POSTGRES_PASSWORD: project
      POSTGRES_USER: project
      POSTGRES_DB: project

  web:
    image: "nginx:${NGINX_VERSION:-1.21}"
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/:/etc/nginx/conf.d
    container_name: symf_test_nginx

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: symf_redis

#  queue:
#    image: "schickling/beanstalkd:${QUEUE_VERSION:-latest}"
#    ports:
#      - "11300:11300"
#    init: true
#    container_name: symf_queue

#  worker:
#    build:
#      context: .
#      args:
#        - PHP_VERSION=${PHP_VERSION:-8.1.8}
#      dockerfile: .docker/php/Dockerfile
#    working_dir: /symfony_work
#    user: ${UID:-1000}:${GID:-1000}
#    environment:
#      PHP_IDE_CONFIG: "serverName=DevServer1"
#    restart: unless-stopped
#    entrypoint: ["php", "/symfony_work/bin/console"]
#    command: ["messenger:consume", "pheanstalk", "--limit", "10", "-vv"]
 #   volumes:
 #     - ./:/symfony_work
 #    - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
 #  depends_on:
 #      - queue
  #  container_name: symf_worker
