twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
        paths:
            # allows to use api/templates/ dir in the ApiKernel
            "%kernel.project_dir%/api/templates": ~
